%==========================================================================
% >>>>>>>>>>>>>>>>>> FUNCTION SF-12: COLLISION AVOIDANCE <<<<<<<<<<<<<<<<<<<
%==========================================================================
% Created by Diego Varalda de Almeida
% version 1.0 - March 30th, 2016.

% DESCRIPTION: This function will receive the trajectory generated by ohter
% command and determine if this trajectory may cause a collision of the
% robot with some object (by calling the respective primary function). If a
% collision is detected, a new trajectory is created free of collisions.
% For future updates this function may work together with vision systems.
% Refer to section 4 of documentation for details. 
%==========================================================================
function SF_Collision_Avoidance(function_variables, eventdata, handles)
%Use this function for avoiding collision with objects
%This function makes use of the function D: Collision Check
%To be implemented in the future
%>>> END OF FUNCTION